// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL6uALKiZDTW6-jC8EPO3V2PlFAfRqfns',
    appId: '1:43637078259:web:b2b32a0fd0f0ca6f201f86',
    messagingSenderId: '43637078259',
    projectId: 'lafacil-7d1ed',
    authDomain: 'lafacil-7d1ed.firebaseapp.com',
    storageBucket: 'lafacil-7d1ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLei52XR2DIVblDq0Rz_O4AhRkmaOQUxk',
    appId: '1:43637078259:android:8e11ea5068cca060201f86',
    messagingSenderId: '43637078259',
    projectId: 'lafacil-7d1ed',
    storageBucket: 'lafacil-7d1ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6UbTn4yAVI0yP6LQ7prnceU50PiHrqO8',
    appId: '1:43637078259:ios:46d99f0e8c64c9a1201f86',
    messagingSenderId: '43637078259',
    projectId: 'lafacil-7d1ed',
    storageBucket: 'lafacil-7d1ed.appspot.com',
    iosClientId: '43637078259-qpfcl4eoqn5a40qsh749n97hp7ctt4s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.voiceCallZegocloud',
  );
}
